App/Models/Tasks.cs
using App.Resources;
using System;
using System.ComponentModel.DataAnnotations;



namespace App.Models
{
    public class Tasks
    {
        [Required]
        public long Id { get; set; }
        [Required]
        public long User_id { get; set; }
        [Required(ErrorMessageResourceName = "Error_partner", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Partner", ResourceType = typeof(Resource))]
        public string Partner { get; set; }
        [Display(Name = "Description", ResourceType = typeof(Resource))]
        public string Description { get; set; }
        [Required(ErrorMessageResourceName = "Error_place_of_receipt", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Place_of_receipt", ResourceType = typeof(Resource))]
        public string Place_of_receipt { get; set; }
        [Required(ErrorMessageResourceName = "Error_time_of_receipt", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Time_of_receipt", ResourceType = typeof(Resource))]
        public DateTime? Time_of_receipt { get; set; }
        [Required(ErrorMessageResourceName = "Error_place_of_delivery", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Place_of_delivery", ResourceType = typeof(Resource))]
        public string Place_of_delivery { get; set; }
        [Required(ErrorMessageResourceName = "Error_time_of_delivery", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Time_of_delivery", ResourceType = typeof(Resource))]
        public DateTime? Time_of_delivery { get; set; }
        [Display(Name = "Other_stops", ResourceType = typeof(Resource))]
        public string Other_stops { get; set; }
        [Display(Name = "Id_cargo", ResourceType = typeof(Resource))]
        public string Id_cargo { get; set; }
        [Display(Name = "Storage_time", ResourceType = typeof(Resource))]
        public string Storage_time { get; set; }
        [Display(Name = "Completed", ResourceType = typeof(Resource))]
        public bool Completed { get; set; }
        [Display(Name = "Completion_time", ResourceType = typeof(Resource))]
        public DateTime? Completion_time { get; set; }
        [Display(Name = "Time_of_delay", ResourceType = typeof(Resource))]
        public string Time_of_delay { get; set; }
        [Display(Name = "Payment", ResourceType = typeof(Resource))]
        public string Payment { get; set; }
        [Display(Name = "Final_Payment", ResourceType = typeof(Resource))]
        public string Final_Payment { get; set; }
        [Display(Name = "Penalty", ResourceType = typeof(Resource))]
        public string Penalty { get; set; }
        [Display(Name = "Date", ResourceType = typeof(Resource))]
        public DateTime Date { get; set; } = DateTime.Now;
    }   
        
}

App/Controllers/TasksController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using App.Data;
using Microsoft.AspNetCore.Http;
using System.Data;
using System.IO;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.InkML;
using System.Text;
using iTextSharp.text;
using iTextSharp.text.pdf;
using X.PagedList;
using Tasks = App.Models.Tasks;
using Document = iTextSharp.text.Document;
using Font = iTextSharp.text.Font;
using PageSize = iTextSharp.text.PageSize;
using Paragraph = iTextSharp.text.Paragraph;
using System.Web;
using DocumentFormat.OpenXml.Presentation;
using System.Collections.Generic;
using DocumentFormat.OpenXml.Bibliography;
using Org.BouncyCastle.Math.EC.Multiplier;
using Microsoft.Data.SqlClient;
using System.Web.WebPages;
using Microsoft.CodeAnalysis.CSharp;

namespace App.Controllers
{
    public class TasksController : BaseController
    {
        private readonly ApplicationDbContext _context;

        public TasksController(ApplicationDbContext context)
        {
            _context = context;
        }

            // GET: Tasks
        public IActionResult Tasks_page(string searchString, string sortOrder, string currentFilter, int? page)
        {
            @ViewBag.tasks = "active";
            if (HttpContext.Session.GetString("Id") == null)
            {
                return RedirectToAction("Login_page", "Login");
            }
            else
            {
                ViewBag.CurrentSort = sortOrder;
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;

                var tasks = from t in _context.Tasks select t;
                // which column to sort 
                ViewBag.PartnerSortParm = sortOrder == "Partner" ? "Partner_desc" : "Partner";
                ViewBag.DescriptionSortParm = sortOrder == "Description" ? "Description_desc" : "Description";
                ViewBag.Place_of_receiptSortParm = sortOrder == "Place_of_receipt" ? "Place_of_receipt_desc" : "Place_of_receipt";
                ViewBag.Time_of_receiptSortParm = sortOrder == "Time_of_receipt" ? "Time_of_receipt_desc" : "Time_of_receipt";
                ViewBag.Place_of_deliverySortParm = sortOrder == "Place_of_delivery" ? "Place_of_delivery_desc" : "Place_of_delivery";
                ViewBag.Time_of_deliverySortParm = sortOrder == "Time_of_delivery" ? "Time_of_delivery_desc" : "Time_of_delivery";
                ViewBag.Other_stopsSortParm = sortOrder == "Other_stops" ? "Other_stops_desc" : "Other_stops";
                ViewBag.Id_cargoSortParm = sortOrder == "Id_cargo" ? "Id_cargo_desc" : "Id_cargo";
                ViewBag.Storage_timeSortParm = sortOrder == "Storage_time" ? "Storage_time_desc" : "Storage_time";
                ViewBag.CompletedSortParm = sortOrder == "Completed" ? "Completed_desc" : "Completed";
                ViewBag.Completion_timeSortParm = sortOrder == "Completion_time" ? "Completion_time_desc" : "Completion_time";
                ViewBag.Time_of_delaySortParm = sortOrder == "Time_of_delay" ? "Time_of_delay_desc" : "Time_of_delay";
                ViewBag.PaymentSortParm = sortOrder == "Payment" ? "Payment_desc" : "Payment";
                ViewBag.Final_PaymentSortParm = sortOrder == "Final_Payment" ? "Final_Payment_desc" : "Final_Payment";
                ViewBag.PenaltySortParm = sortOrder == "Penalty" ? "Penalty_desc" : "Penalty";
                ViewBag.DateSortParm = String.IsNullOrEmpty(sortOrder) ? "Date_desc" : "";
                //search
                if (!String.IsNullOrEmpty(searchString))
                {
                    ViewBag.searchPlaceHolder = searchString;
                    tasks = tasks.Where(s => s.Partner!.Contains(searchString) || s.Place_of_receipt!.Contains(searchString) || s.Place_of_delivery!.Contains(searchString) || s.Time_of_delivery.ToString()!.Contains(searchString) || (s.Id_cargo!.Contains(searchString) || s.Storage_time!.Contains(searchString) || s.Completion_time.ToString()!.Contains(searchString) || s.Payment!.Contains(searchString) || s.Final_Payment!.Contains(searchString) || s.Penalty!.Contains(searchString) || s.Date.ToString()!.Contains(searchString)));
                }
                else
                {
                    ViewBag.searchPlaceHolder = App.Resources.Resource.search;
                }
                // sort order
                switch (sortOrder)
                {
                    case "Partner_desc":
                        tasks = tasks.OrderByDescending(s => s.Partner);
                        break;
                    case "Partner":
                        tasks = tasks.OrderBy(s => s.Partner);
                        break;
                    case "Description_desc":
                        tasks = tasks.OrderByDescending(s => s.Description);
                        break;
                    case "Description":
                        tasks = tasks.OrderBy(s => s.Description);
                        break;
                    case "Place_of_receipt_desc":
                        tasks = tasks.OrderByDescending(s => s.Place_of_receipt);
                        break;
                    case "Place_of_receipt":
                        tasks = tasks.OrderBy(s => s.Place_of_receipt);
                        break;
                    case "Time_of_receipt_desc":
                        tasks = tasks.OrderByDescending(s => s.Time_of_receipt);
                        break;
                    case "Time_of_receipt":
                        tasks = tasks.OrderBy(s => s.Time_of_receipt);
                        break;
                    case "Place_of_delivery_desc":
                        tasks = tasks.OrderByDescending(s => s.Place_of_delivery);
                        break;
                    case "Place_of_delivery":
                        tasks = tasks.OrderBy(s => s.Place_of_delivery);
                        break;
                    case "Time_of_delivery_desc":
                        tasks = tasks.OrderByDescending(s => s.Time_of_delivery);
                        break;
                    case "Time_of_delivery":
                        tasks = tasks.OrderBy(s => s.Time_of_delivery);
                        break;
                    case "Other_stops_desc":
                        tasks = tasks.OrderByDescending(s => s.Other_stops);
                        break;
                    case "Other_stops":
                        tasks = tasks.OrderBy(s => s.Other_stops);
                        break;
                    case "Id_cargo_desc":
                        tasks = tasks.OrderByDescending(s => s.Id_cargo);
                        break;
                    case "Id_cargo":
                        tasks = tasks.OrderBy(s => s.Id_cargo);
                        break;
                    case "Storage_time_desc":
                        tasks = tasks.OrderByDescending(s => s.Storage_time);
                        break;
                    case "Storage_time":
                        tasks = tasks.OrderBy(s => s.Storage_time);
                        break;
                    case "Completed_desc":
                        tasks = tasks.OrderByDescending(s => s.Completed);
                        break;
                    case "Completed":
                        tasks = tasks.OrderBy(s => s.Completed);
                        break;
                    case "Completion_time_desc":
                        tasks = tasks.OrderByDescending(s => s.Completion_time);
                        break;
                    case "Completion_time":
                        tasks = tasks.OrderBy(s => s.Completion_time);
                        break;
                    case "Time_of_delay_desc":
                        tasks = tasks.OrderByDescending(s => s.Time_of_delay);
                        break;
                    case "Time_of_delay":
                        tasks = tasks.OrderBy(s => s.Time_of_delay);
                        break;
                    case "Payment_desc":
                        tasks = tasks.OrderByDescending(s => s.Payment);
                        break;
                    case "Payment":
                        tasks = tasks.OrderBy(s => s.Payment);
                        break;
                    case "Final_Payment_desc":
                        tasks = tasks.OrderByDescending(s => s.Final_Payment);
                        break;
                    case "Final_Payment":
                        tasks = tasks.OrderBy(s => s.Final_Payment);
                        break;
                    case "Penalty_desc":
                        tasks = tasks.OrderByDescending(s => s.Penalty);
                        break;
                    case "Penalty":
                        tasks = tasks.OrderBy(s => s.Penalty);
                        break;
                    case "Date_desc":
                        tasks = tasks.OrderByDescending(s => s.Date);
                        break;
                    default:
                        tasks = tasks.OrderBy(s => s.Date);
                        break;
                }

                int pageSize = 10; //Show x rows every time
                int pageNumber = (page ?? 1);
                return View(tasks.ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: Tasks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tasks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,User_id,Partner,Description,Place_of_receipt,Time_of_receipt,Place_of_delivery,Time_of_delivery,Other_stops,Id_cargo,Storage_time,Completed,Completion_time,Time_of_delay,Payment,Final_Payment,Penalty,Date")] Tasks tasks)

App/Views/Tasks/Edit.cshtml
@model App.Models.Tasks

@{
    ViewData["Title"] = App.Resources.Resource.Edit_tasks;
}

<!-- partial -->
<div class="main-panel main">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin">
                <div class="d-flex justify-content-between flex-wrap">
                    <div class="forms">
                        <div class="me-md-3 me-xl-5 form-title">
                            <h2>@ViewData["Title"]</h2>
                        </div>
                        <hr />
                        <form asp-action="Edit" asp-controller="Tasks" class="columns">
                            <div>
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="Id" />
                                <div class="form-group">
                                    <label asp-for="Partner" class="control-label"></label>
                                    <input asp-for="Partner" class="form-control" />
                                    <span asp-validation-for="Partner" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Description" class="control-label"></label>
                                    <input asp-for="Description" class="form-control" />
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Place_of_receipt" class="control-label"></label>
                                    <input asp-for="Place_of_receipt" class="form-control" />
                                    <span asp-validation-for="Place_of_receipt" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Time_of_receipt" class="control-label"></label>
                                    <input asp-for="Time_of_receipt" class="form-control" />
                                    <span asp-validation-for="Time_of_receipt" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Place_of_delivery" class="control-label"></label>
                                    <input asp-for="Place_of_delivery" class="form-control" />
                                    <span asp-validation-for="Place_of_delivery" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Time_of_delivery" class="control-label"></label>
                                    <input asp-for="Time_of_delivery" class="form-control" />
                                    <span asp-validation-for="Time_of_delivery" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Other_stops" class="control-label"></label>
                                    <input asp-for="Other_stops" class="form-control" />
                                    <span asp-validation-for="Other_stops" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Id_cargo" class="control-label"></label>
                                    <input asp-for="Id_cargo" class="form-control" />
                                    <span asp-validation-for="Id_cargo" class="text-danger"></span>
                                </div>
                            </div>
                            <div>
                                <div class="form-group">
                                    <label asp-for="Storage_time" class="control-label"></label>
                                    <input asp-for="Storage_time" class="form-control" />
                                    <span asp-validation-for="Storage_time" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Completion_time" class="control-label"></label>
                                    <input asp-for="Completion_time" class="form-control" />
                                    <span asp-validation-for="Completion_time" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Time_of_delay" class="control-label"></label>
                                    <input asp-for="Time_of_delay" class="form-control" />
                                    <span asp-validation-for="Time_of_delay" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Payment" class="control-label"></label>
                                    <input asp-for="Payment" class="form-control" />
                                    <span asp-validation-for="Payment" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Final_Payment" class="control-label"></label>
                                    <input asp-for="Final_Payment" class="form-control" />
                                    <span asp-validation-for="Final_Payment" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Penalty" class="control-label"></label>
                                    <input asp-for="Penalty" class="form-control" />
                                    <span asp-validation-for="Penalty" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Date" class="control-label"></label>
                                    <input asp-for="Date" class="form-control" />
                                    <span asp-validation-for="Date" class="text-danger"></span>
                                </div>
                                <div class="form-group form-check">
                                    <label class="toggler-wrapper style-1">
                                        <input class="form-check-input" asp-for="Completed" /> 
                                        <div class="toggler-slider">
                                            <div class="toggler-knob"></div>
                                        </div>
                                        <span>@Html.DisplayNameFor(model => model.Completed)</span>
                                    </label>
                                </div>
                            </div>
                            <br />
                            <div class="form-group center2">
                                <input type="submit" value="Mentés" class="btn btn-primary" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

App/Views/Tasks/_Settings.cshtml
@model IEnumerable<App.Models.Tasks>

<div class="modal fade" id="addSettings">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addSettingsLabel">
                    @App.Resources.Resource.Tasks_title;
                </h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span>x</span>
                </button>
            </div>
            <div class="modal-body" >
                <form class="popup" asp-action="Modal" asp-controller="Tasks">
                    <div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Partner)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Description)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Place_of_receipt)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Time_of_receipt)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Place_of_delivery)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Time_of_delivery)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Other_stops)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Id_cargo)
                            </label>
                        </div>
                    </div>
                    <div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Storage_time)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Completion_time)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Time_of_delay)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Payment)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Final_Payment)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Penalty)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Date)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" /> @Html.DisplayNameFor(model => model.Completed)
                            </label>
                        </div>
                    </div>
                    <br />
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" data-save="modal">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}