App/Controllers/AdminController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using App.Data;
using DocumentFormat.OpenXml.InkML;
using Users = App.Models.Users;
using Microsoft.AspNetCore.Http;
using X.PagedList;

namespace App.Controllers
{
    public class AdminController : BaseController
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Registration
        public IActionResult Admin_page(string searchString, string sortOrder, string currentFilter, int? page)
        {
 

            @ViewBag.admin = "active";
            if (HttpContext.Session.GetString("Id") == null)
            {
                return RedirectToAction("Login_page", "Login");
            }
            else
            {
                ViewBag.CurrentSort = sortOrder;
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;
                var users = from u in _context.Users select u;
                // which column to sort 
                ViewBag.UserNameSortParm = sortOrder == "UserName" ? "UserName_desc" : "UserName";
                ViewBag.EmailSortParm = sortOrder == "Email" ? "Email_desc" : "Email";
                ViewBag.PasswordSortParm = sortOrder == "Password" ? "Password_desc" : "Password";
                ViewBag.RoleSortParm = sortOrder == "Role" ? "Role_desc" : "Role";
                ViewBag.PhoneNumberSortParm = sortOrder == "PhoneNumber" ? "PhoneNumber_desc" : "PhoneNumber";
                ViewBag.NameSortParm = sortOrder == "Name" ? "Name_desc" : "Name";
                //search
                if (!String.IsNullOrEmpty(searchString))
                {
                    ViewBag.searchPlaceHolder = searchString;
                    users = users.Where(s => s.PhoneNumber.ToString()!.Contains(searchString) ||  s.Name!.Contains(searchString) || s.UserName!.Contains(searchString) || s.Email!.Contains(searchString) || s.Role!.Contains(searchString));
                }
                else
                {
                    ViewBag.searchPlaceHolder = App.Resources.Resource.search;
                }

                switch (sortOrder)
                {
                    case "UserName_desc":
                        users = users.OrderByDescending(s => s.UserName);
                        break;
                    case "UserName":
                        users = users.OrderBy(s => s.UserName);
                        break;
                    case "Email_desc":
                        users = users.OrderByDescending(s => s.Email);
                        break;
                    case "Email":
                        users = users.OrderBy(s => s.Email);
                        break;
                    case "Password_desc":
                        users = users.OrderByDescending(s => s.PasswordHash);
                        break;
                    case "Password":
                        users = users.OrderBy(s => s.PasswordHash);
                        break;
                    case "Role_desc":
                        users = users.OrderByDescending(s => s.Role);
                        break;
                    case "Role":
                        users = users.OrderBy(s => s.Role);
                        break;
                    case "PhoneNumber_desc":
                        users = users.OrderByDescending(s => s.Role);
                        break;
                    case "Phone":
                        users = users.OrderBy(s => s.Role);
                        break;
                    case "Name_desc":
                        users = users.OrderByDescending(s => s.Role);
                        break;
                    case "Name":
                        users = users.OrderBy(s => s.Role);
                        break;
                    default:
                        break;
                }

                int pageSize = 10; //Show x rows every time
                int pageNumber = (page ?? 1);
                return View(users.ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: Registration/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Registration/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,Name,Email,PhoneNumber,PasswordHash,Role")] Users users)
        {
            if (UserNameExists(users.UserName))
            {
                TempData["LoginErrorMessage"] = App.Resources.Resource.LoginErrorMessage;
                return View(users);
            }
            else
            {
                users.PasswordHash = md5.CreateMD5(users.PasswordHash);
                _context.Add(users);

                await _context.SaveChangesAsync();
                return RedirectToAction("Admin_page");
            }    
            
        }

        // GET: Registration/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users.FindAsync(id);
            if (users == null)
            {
                return NotFound();
            }
            return View(users);
        }

        // POST: Registration/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,Name,Email,PhoneNumber,PasswordHash,LoginErrorMessage,Role")] Users users)
        {
            if (id != users.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    users.PasswordHash = md5.CreateMD5(users.PasswordHash);
                    _context.Update(users);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsersExists(users.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Admin_page));
            }
            return View(users);
        }

        // GET: Registration/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // POST: Registration/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var users = await _context.Users.FindAsync(id);
            _context.Users.Remove(users);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Admin_page));
        }

        private bool UsersExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
        private bool UserNameExists(string UserName)
        {
            return _context.Users.Any(e => e.UserName == UserName);
        }
    }
}

App/Controllers/BaseController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Text.RegularExpressions;
using Controller = Microsoft.AspNetCore.Mvc.Controller;

namespace App.Controllers
{
    public class BaseController : Controller
    {
        public BaseController()
        {

        }
        public IActionResult Language(string culture, string returnUrl)
        {
            Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
               CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
               new CookieOptions { Expires = DateTimeOffset.UtcNow.AddDays(1) }
           );

            return LocalRedirect(returnUrl);
        }
    }
}

App/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor Accessor;

@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options


@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    //language chooser
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = new List<SelectListItem>();
    cultureItems.AddRange(LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.Name.ToUpper() })
        .ToList());
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

@{
    var role = -1;
    switch (Accessor.HttpContext.Session.GetString("Role"))
    {
        case "tasks":
            role = 1;
            break;
        case "cargoes":
            role = 2;
            break;
        case "roads":
            role = 3;
            break;
        case "storages":
            role = 4;
            break;
        case "trucks":
            role = 5;
            break;
        case "expenses":
            role = 6;
            break;
        case "admin":
            role = 10;
            break;
        default:
            role = 0;
            break;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CargoTruck</title>

    <!-- plugin css for this page -->
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <!-- End plugin css for this page -->
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="img-background">
    <header>
        <nav class="fixednavbar navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container navbar-margin">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidebar" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <!--Login menu links -->
                    <partial name="_LoginPartial" />              
                    <ul class="navbar-nav flex-grow-1">  
                        <li class="nav-item top-nav-item @ViewBag.home">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Privacy">@App.Resources.Resource.Privacy</a>
                        </li>
                    </ul>
                    <!--asp-for="Language"-->
                    <div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
                        <form id="selectLanguage" asp-controller="Base" asp-action="Language" asp-route-returnUrl="@returnUrl" method="post" class="form-horizontal" role="form">
                            <select class="form-control nav-language selectpicker" name="culture" onchange="this.form.submit();" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
                            </select>
                        </form>
                    </div>

                </div>
            </div>
        </nav>
    </header>



    @if (Accessor.HttpContext.Session.GetString("Id") != null)
    {
        <!-- Sidebar -->
        <nav class="sidebar sidebar-offcanvas navbar-collapse" id="sidebar">
            <ul id="nav" class="nav">
                @if (role == 0 || role == 10 || role == 1)
                {
                    <li class="nav-item @ViewBag.tasks">
                        <a  class="nav-link"  asp-area="" asp-controller="Tasks" asp-action="Tasks_page">
                            <span class="menu-title">@App.Resources.Resource.Tasks_title</span><span class="arrow">&#8250;</span>
                        </a>
                    </li>
                }
                @if (role == 0 || role == 10 || role == 2)
                {
                    <li class="nav-item @ViewBag.cargoes">
                        <a class="nav-link " asp-area="" asp-controller="Cargoes" asp-action="Cargoes_page">
                            <span class="menu-title">@App.Resources.Resource.Cargoes</span><span class="arrow">&#8250;</span>
                        </a>
                    </li>
                }
                @if (role == 0 || role == 10 || role == 3)
                {
                    <li class="nav-item @ViewBag.roads">
                        <a class="nav-link " asp-area="" asp-controller="Roads" asp-action="Roads_page">
                            <span class="menu-title">@App.Resources.Resource.Roads</span><span class="arrow">&#8250;</span>
                        </a>
                    </li>
                }
                @if (role == 0 || role == 10 || role == 4)
                {
                    <li class="nav-item @ViewBag.storages">
                        <a class="nav-link " asp-area="" asp-controller="Storages" asp-action="Storages_page">
                            <span class="menu-title">@App.Resources.Resource.Warehouse</span><span class="arrow">&#8250;</span>
                        </a>
                    </li>
                }
                @if (role == 0 || role == 10 || role == 5)
                {
                    <li class="nav-item @ViewBag.trucks">
                        <a class="nav-link " asp-area="" asp-controller="Trucks" asp-action="Trucks_page">
                            <span class="menu-title">@App.Resources.Resource.Trucks</span><span class="arrow">&#8250;</span>
                        </a>
                    </li>
                }
                @if (role == 0 || role == 10 || role == 6)
                {
                    <li class="nav-item @ViewBag.expenses">
                        <a class="nav-link " asp-area="" asp-controller="Expenses" asp-action="Expenses_page">
                            <span class="menu-title">@App.Resources.Resource.Expenses</span><span class="arrow">&#8250;</span>
                        </a>
                    </li>
                }
                @if (role == 10)
                {
                    <li class="nav-item @ViewBag.admin">
                        <a class="nav-link " asp-area="" asp-controller="Admin" asp-action="Admin_page">
                            <span class="menu-title">@App.Resources.Resource.Admin_page</span><span class="arrow">&#8250;</span>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    }


    <div class="container">
        <main role="main" class="pb-3 margintop">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CargoTruck - <a asp-area="" asp-controller="Home" asp-action="Privacy">@App.Resources.Resource.Privacy</a>
        </div>
    </footer>

    @section scripts{
        <script type="text/javascript" src="~/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="~/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="~/js/bootstrap.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

        <script type="text/javascript" src="~/js/site.js"></script> <!--The app's js file-->
    }
    @RenderSection("scripts", required: false)
</body>
</html>